name: pliiz_web
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:

  sdk: '>=3.0.0 <4.0.0'
  #sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  get: ^4.6.5
  flutter_svg: ^2.0.4
  flutter_bounceable: ^1.1.0
  google_fonts: ^4.0.3
  provider: ^6.0.5
  shared_preferences: ^2.0.20
  dio: ^4.0.6
  cached_network_image: ^3.2.3
  get_it: ^7.2.0
  firebase_core: ^3.4.0
  #firebase_core: ^2.8.0
  firebase_auth: ^5.2.0
  #firebase_auth: ^4.3.0
  firebase_database: ^11.1.0
 # firebase_database: ^10.1.0
  cloud_firestore: ^5.3.0
 # cloud_firestore: ^4.4.5
  fluttertoast: ^8.2.1
  google_sign_in: ^6.0.2
  url_strategy: ^0.2.0
  flutter_facebook_auth: '^3.5.0'
  get_storage: any
  widgets_to_image: ^0.0.2
  image_downloader_web: ^2.0.2
  custom_qr_generator: ^0.1.2
  #short_uuids: ^2.0.0
  file_picker: ^5.2.6
  image_picker: ^0.8.7+1
  url_launcher: ^6.1.11
  firebase_storage: any
  oktoast: any
  multi_select_flutter: ^4.1.3
  web_image_downloader: ^1.0.1
  multiple_search_selection: ^2.4.5
  panara_dialogs: ^0.1.4
  multiselect_formfield: ^0.1.7
  pdfx: ^2.6.0
  #pdfx: ^2.3.0
  flutter_multi_select_items: ^0.4.2
  universal_html: ^2.2.1
  qr_svg_generator: ^0.0.1
  qr: ^3.0.1
  syncfusion_flutter_barcodes: ^21.1.39
  widget_to_image: ^2.0.0
  firebase_messaging: any
  http: any
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/


